import AppFooter from "@/components/AppFooter";
import AppNavbar from "@/components/AppNavbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ alumns, homeworks, notes }) {
  return (
    <>
      <AppNavbar />
      <div className="container mx-auto py-6 px-1">
        <div className="grid grid-flow-row grid-cols-1 md:grid-cols-2 gap-5">
          <div className="col-span-1 md:col-span-2 h-full">{alumns}</div>
          <div className="h-full">{homeworks}</div>
          <div className="h-full">{notes}</div>
        </div>
      </div>
      <AppFooter />
    </>
  );
}
